# Generated by Django 5.1.15 on 2026-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this project in the hero slider on the homepage.'),
        ),
    ]
