# Generated by Django 5.1.15 on 2026-03-19 11:02

import django.db.models.deletion
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    ProjectCategory = apps.get_model("projects", "ProjectCategory")
    defaults = [
        {"slug": "updates", "label": "Updates", "order": 0},
        {"slug": "events", "label": "Events", "order": 1},
        {"slug": "stories", "label": "Stories", "order": 2},
    ]
    for d in defaults:
        ProjectCategory.objects.get_or_create(slug=d["slug"], defaults=d)


def reverse_categories(apps, schema_editor):
    ProjectCategory = apps.get_model("projects", "ProjectCategory")
    ProjectCategory.objects.filter(slug__in=["updates", "events", "stories"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for filtering (Updates, Events, Stories).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory'),
        ),
        migrations.RunPython(create_default_categories, reverse_categories),
    ]
