# Generated by Django 5.1.15 on 2026-03-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('credentials', models.CharField(blank=True, help_text='e.g. PhD, MSc, BSc', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short biography for the team member.')),
                ('image', models.ImageField(blank=True, upload_to='team/%Y/%m/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as the main featured leader (only one should be featured).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first).')),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
