# Generated by Django 5.1.15 on 2026-03-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='education',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='focus_areas',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teammember',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text="List of {value, label} for featured leader, e.g. [{'value': '15+', 'label': 'Years Experience'}]"),
        ),
    ]
